/**
 * Word-native deliverables. Lawyers live in Word — until output lands as a
 * .docx, an engine is a demo. Renders the MFN compendium and side-letter
 * draft sets as clean documents with a numbered Sources annex: every
 * in-text marker [n] resolves to the verbatim quoted clause and its
 * ontology id, so the verification story survives the export.
 */

import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from 'docx';
import type { VerifiedCitation } from '../engine/citations.js';

/** Citations arrive from the UI payload with an optional verified flag. */
type Citation = Omit<VerifiedCitation, 'verified'> & { verified?: boolean };

// ── shared bits ──────────────────────────────────────────────────────────

const FONT = 'Georgia';

function h1(text: string): Paragraph {
  return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text, font: FONT })] });
}

function h2(text: string): Paragraph {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 280 }, children: [new TextRun({ text, font: FONT })] });
}

function body(text: string, opts: { italics?: boolean; bold?: boolean } = {}): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text, font: FONT, size: 22, italics: opts.italics, bold: opts.bold })],
  });
}

function meta(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 80 },
    children: [new TextRun({ text, font: FONT, size: 18, color: '6b6b70' })],
  });
}

function bodyWithMarker(text: string, marker: number | null): Paragraph {
  const children = [new TextRun({ text, font: FONT, size: 22 })];
  if (marker !== null) {
    children.push(new TextRun({ text: ` [${marker}]`, font: FONT, size: 18, superScript: true, color: 'c45f3f' }));
  }
  return new Paragraph({ spacing: { after: 120 }, children });
}

class SourceAnnex {
  private sources: Array<{ citation: Citation }> = [];

  add(citation: Citation | undefined | null): number | null {
    if (!citation || !citation.quote) return null;
    this.sources.push({ citation });
    return this.sources.length;
  }

  addAll(citations: Citation[] | undefined): number[] {
    return (citations ?? []).map((c) => this.add(c)).filter((n): n is number => n !== null);
  }

  paragraphs(): Paragraph[] {
    if (this.sources.length === 0) return [];
    const out = [h2('Sources')];
    out.push(
      meta('Every numbered source below was verified verbatim against the engagement record at generation time. ✓ = verified; ✗ = the quote was not found in the cited source and must be checked by hand.'),
    );
    this.sources.forEach(({ citation }, i) => {
      const mark = citation.verified === false ? '✗' : '✓';
      out.push(
        new Paragraph({
          spacing: { after: 100 },
          children: [
            new TextRun({ text: `[${i + 1}] ${mark} ${citation.sourceType} ${citation.sourceId}: `, font: FONT, size: 18, bold: true }),
            new TextRun({ text: `“${citation.quote}”`, font: FONT, size: 18, italics: true }),
          ],
        }),
      );
    });
    return out;
  }
}

function disclaimer(): Paragraph[] {
  return [
    new Paragraph({ spacing: { before: 360 }, children: [] }),
    meta('Generated by Forge, a fund formation engine. Drafting support only; not legal advice. Review by qualified counsel required before use.'),
  ];
}

async function pack(title: string, children: Paragraph[]): Promise<Buffer> {
  const doc = new Document({
    title,
    sections: [{ children }],
    styles: {
      default: { document: { run: { font: FONT } } },
    },
  });
  return Packer.toBuffer(doc);
}

// ── MFN compendium ───────────────────────────────────────────────────────

interface MfnPayload {
  fundName: string;
  basis: { sourceType: string; sourceId: string; sourceClause: string } | null;
  thresholdUsd: number | null;
  windowDays: number | null;
  deliveryDate: string | null;
  electionDeadline: string | null;
  electors: Array<{ name: string; commitmentUsd: number }>;
  entries: Array<{
    granteeName: string;
    topic: string;
    heading: string;
    text: string;
    classification: string;
    rationale: string;
    citation: Citation;
    electableBy: string[];
  }>;
}

function usdText(n: number | null): string {
  if (n === null) return '–';
  return `$${n.toLocaleString('en-US')}`;
}

export async function mfnCompendiumDocx(payload: MfnPayload): Promise<Buffer> {
  const annex = new SourceAnnex();
  const children: Paragraph[] = [
    h1(`Side Letter Compendium: ${payload.fundName}`),
    meta(
      `Eligibility threshold ${usdText(payload.thresholdUsd)} · election window ${payload.windowDays ?? '–'} days` +
        (payload.deliveryDate ? ` · delivered ${payload.deliveryDate}` : '') +
        (payload.electionDeadline ? ` · elections close ${payload.electionDeadline}` : ''),
    ),
  ];

  if (payload.basis) {
    const n = annex.add({
      sourceType: payload.basis.sourceType as Citation['sourceType'],
      sourceId: payload.basis.sourceId,
      quote: payload.basis.sourceClause,
    });
    children.push(bodyWithMarker(`MFN basis: “${payload.basis.sourceClause}”`, n));
  }

  children.push(h2('Eligible electing investors'));
  for (const e of payload.electors) {
    children.push(body(`• ${e.name}: ${usdText(e.commitmentUsd)}`));
  }

  const groups: Array<[string, string]> = [
    ['electable', 'Part A — Provisions available for election'],
    ['excluded_recipient_specific', 'Part B — Provisions excluded as recipient-specific'],
  ];
  for (const [cls, title] of groups) {
    const entries = payload.entries.filter((e) => e.classification === cls);
    if (entries.length === 0) continue;
    children.push(h2(title));
    for (const e of entries) {
      const n = annex.add(e.citation);
      children.push(body(`${e.heading} — granted to ${e.granteeName}`, { bold: true }));
      children.push(bodyWithMarker(e.text, n));
      children.push(meta(`Classification rationale: ${e.rationale}`));
      if (cls === 'electable' && e.electableBy.length > 0) {
        children.push(meta(`Electable by: ${e.electableBy.join(', ')}`));
      }
    }
  }

  children.push(...annex.paragraphs(), ...disclaimer());
  return pack(`Side Letter Compendium — ${payload.fundName}`, children);
}

// ── Side letter drafts ───────────────────────────────────────────────────

interface SideLetterPayload {
  fundName: string;
  investorName: string;
  drafts: Array<{
    label: string;
    rationale: string;
    clauses: Array<{ term: string; tier: string; text: string; citations?: Citation[] }>;
  }>;
}

const TIER_LABEL: Record<string, string> = {
  model_language: 'model language',
  adapted_precedent: 'adapted precedent',
  fresh_drafting: 'fresh drafting',
};

export async function sideLettersDocx(payload: SideLetterPayload): Promise<Buffer> {
  const annex = new SourceAnnex();
  const children: Paragraph[] = [
    h1(`Side Letter Drafts — ${payload.investorName}`),
    meta(`${payload.fundName} · three drafting strategies · every clause labelled with the source of its language`),
  ];

  payload.drafts.forEach((d, i) => {
    children.push(h2(`Draft ${i + 1} — ${TIER_LABEL[d.label] ?? d.label}`));
    children.push(meta(d.rationale));
    for (const c of d.clauses) {
      const ns = annex.addAll(c.citations);
      children.push(body(`${c.term} (${TIER_LABEL[c.tier] ?? c.tier})`, { bold: true }));
      children.push(bodyWithMarker(c.text, ns.length > 0 ? ns[0] : null));
      if (ns.length > 1) children.push(meta(`Additional sources: ${ns.slice(1).map((n) => `[${n}]`).join(' ')}`));
    }
  });

  children.push(...annex.paragraphs(), ...disclaimer());
  return pack(`Side Letter Drafts — ${payload.investorName}`, children);
}
